### ISSUE TITLE
Loader mask not taking full screen height and width

### ISSUE THREAD

**Issue by deepak3387** [regrunge/react-fullpage-custom-loader#1]
I am using react-fullpage-custom-loader in one of the application and I am facing issue with mask size.
Actually its not taking complete height and width of the screen dynamically.
For example if there is scroll in a page, it won't take the entire screen size.
Is there any way to pass width and height of the mask as parameter from my component?

**Comment by esWeborg** [comment]
Can you post some code? I think it needs to be out of any wrapper or div to work

**Comment by deepak3387** [comment]
> Can you post some code? I think it needs to be out of any wrapper or div to work
below is example snippet of code I am using:
{this.state.showLoader && <MyComponent sentences={"Please Wait..."} 
//Here I am looking for some property to pass custom height and width of mask  
/>}

**Comment by regrunge** [comment]
You should be able to pass 'width' and 'height' as string props ('200px' or '100%' or whatever CSS you can think of).
Hope it helps

**Comment by deepak3387** [comment]
@regrunge Yes, now I am able to pass the width and height property and its working fine. 
Thank you and appreciate your help in this!
